### ISSUE TITLE
[ADDON] - Amazon EBS CSI driver

### ISSUE THREAD

**Issue by kcoleman731** [aws-quickstart/ssp-amazon-eks#25] opened 2021-05-25 19:58 UTC
Add support for EBS CSI via an add-on

https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html

**Comment by camba1** [comment] 2022-03-16 19:35
Closing as it is a duplicate of  #232 which is already closed

**Closed by camba1** 2022-03-16 19:35 UTC
Labels: add-on
